version: '3.8'
services:
  regex-react-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/src
    command: sh -c "cd app && PORT=3001 yarn start"
    ports:
      - "3001:3001"
    stdin_open: true